version: '3.8'

services:
  weather-api:
    build: .
    container_name: weather-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - APP_VERSION=${APP_VERSION}
    restart: always
