apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-deployment
  labels:
    app: weather-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api
          image: abrahimcse/rest-api-weather:latest  # This will be replaced by GitHub Action with your image tag
          ports:
            - containerPort: 5000
          env:
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: weather-api-secret
                  key: WEATHER_API_KEY

